# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'lilt' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lilt
  pod 'Mixpanel'

  target 'liltTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
